version: "3.0"

services:
  envoy:
    build: services/envoy
    ports:
      - "8001:8001"
      - "8100:8080"
    env_file:
      - services/envoy/.env
    restart: always

  app:
    build: services/app
    ports:
      - "6200:6200"
    env_file:
      - services/app/.env
    restart: always

  mongo_bd:
    build: services/mongoDB
    ports:
      - "27017:27017"
    restart: always
