version: "3.0"

services:
  envoy:
    build: services/envoy
    ports:
      - "8001:8001"
      - "8100:8080"
    env_file:
      - services/envoy/.env
    restart: always

  postgres:
    build: services/postgres
    ports:
      - "27017:27017"
    volumes:
      - ./postgres/data:/postgres/data/db
    restart: always
    
  app:
    build: services/app
    ports:
      - "6200:6200"
    env_file:
      - services/app/.env
    restart: always
