version: "3.0"

services:
#  envoy:
#    build: services/envoy
#    ports:
#      - "8001:8001"
#      - "8100:8080"
#    env_file:
#      - services/envoy/.env
#    restart: always

  postgres:
    container_name: "postgress"
    image: postgres:13.3
    enviroment:
      POSTGRES_DB: "general"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - postgres/data:/postgres/data/db
      - postgres/entrypoint.sh:/docker-entrypoint-initdb.d

  app:
    build: services/app
    ports:
      - "6200:6200"
    env_file:
      - services/app/.env
    restart: always
